### ISSUE TITLE
Code is too Java-ish

### ISSUE THREAD

**Issue by eao197** [axomem/nucleus-alpha#14]
That code is:
```cpp
auto app_manager = AppManager();
```
is just a more long version of that code:
```cpp
AppManager app_manager;
```
There is an approach in modern C++ called [*almost always auto* (or AAA)](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/) that dictates such way of variable declarations. But sometimes the old way of a variable declaration is more short and obvious.

The code like:
```cpp
auto app_manager = AppManager();
```
looks like you wanted to write `app_manager = new AppManager()` as in Java, but remembered that you in C++ and decided to declare a variable on the stack.

**Comment by seghcder** [comment]
I am not sure if you are suggesting to change or leave? :-)  I've written more C# (var), Python (none), and Javascript (let) recently. The AAA approach feels more aligned to those too.
