### ISSUE TITLE
Don't think std::vector is required here

### ISSUE THREAD

**Issue by eao197** [axomem/nucleus-alpha#15]
In that code fragment:
```cpp
Logging::Logging(const std::string &name)
{
    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::trace);

    auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(config::log_file, 1024*1024 * 20, 10);
    file_sink->set_level(spdlog::level::trace);
    std::vector<spdlog::sink_ptr> sinks {console_sink, file_sink};

    mylog = std::make_shared<spdlog::logger>(name, sinks.begin(), sinks.end());
```
It's expensive to create `std::vector` with dynamic allocation inside for holding just two smart pointers. An `std::array` without any dynamic allocations can be more appropriate here:
```cpp
std::array<spdlog::sink_ptr, 2> sinks{console_sink, file_sink};
mylog = std::make_shared<spdlog::logger>(name, sinks.begin(), sinks.end());
```
Or even old C-array:
```cpp
spdlog::sink_ptr sinks[] = {console_sink, file_sink};
mylog = std::make_shared<spdlog::logger>(name, std::begin(sinks), std::end(sinks));
```
This is not a mistake, your code is correct. And usage of `std::vector` hasn't any performance impact to your application. But it seems that you haven't a much experience with C++ and because of that I decided to point to that example. Any `std::vector` hide some memory allocations inside and it's better to understand that and avoid that if you have to deal with fixed-size vectors/arrays (with size/capacity known at the compile-time).

**Comment by seghcder** [comment]
I think I was blindly following their example ... no excuse :-)
